### ISSUE TITLE
calculation does not match other implementations

### ISSUE THREAD

**Issue by agrover** [mrhooray/crc-rs#2]
As mentioned in the previous issue, I'm trying to match crcs with LVM's C implementation. CRCs weren't matching until I removed the two negations of "value" in crc32.rs update(). Do those lines serve a purpose, or can they be removed safely?

**Comment by mrhooray** [comment]
these two negations are needed due to reflect Initial Remainder(0xFFFFFFFF) and Final XOR Value(0xFFFFFFFF)  mentioned in the [article](http://www.barrgroup.com/Embedded-Systems/How-To/CRC-Calculation-C-Code)

using negations is common in a few implementations([1](http://create.stephan-brumme.com/crc32/), [2](https://golang.org/src/hash/crc32/crc32.go?s=2467:2493#L83)) and tests show results match IEEE crc32 check value

**Comment by agrover** [comment]
yup, your results match other implementations. I can work around this by inverting values in client code. closing.
